name: Grammar Issue
description: Repeated words or something else that is grammatically incorrect.
title: "[Text]:"
labels: ["Grammar"]
body:
  - type: upload
    id: screenshot
    attributes:
      label: Image
      description: Please provide an image of the of the bug, problem, or mistake you encountered.
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide us with a description of the bug, problem, or mistake you encountered.
    validations:
      required: true
  - type: dropdown
    id: device
    attributes:
      label: Emulator or Flashcart
      description: Are you playing this on a flashcart or an emulator? When in doubt, it's an emulator.
      multiple: false
      options:
        - Emulator
        - Flashcart
    validations:
      required: true
  - type: input
    id: deviceinfo
    attributes:
      label: Emulator or Flashcart Info
      description: Flashcart| Include flashcart name, and device (GBA, DS lite, Game Cube). Emulator| Include name, and device (Pc, 3ds, Android Phone). Also, if emulating use mGBA; VBA-M and Virtual Console are generally less accurate.
    validations:
      required: true
  - type: input
    id: patchversion
    attributes:
      label: Patch Version
      description: Which version of the patch were you using (including the date)?
    validations:
      required: true
  - type: dropdown
    id: gender
    attributes:
      label: Player Gender
      description: Please only pick genders you have seen the issue happen with.
      multiple: true
      options:
        - Boy
        - Girl
    validations:
      required: true
  - type: dropdown
    id: partner
    attributes:
      label: Partner Character
      description: Please only pick partners you have seen the issue happen with.
      multiple: true
      options:
        - RUN-DOR
        - Enzi
        - Killfith
        - Rufeel
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: How did you get this to happen?
      description: Please provide instructions for how to replicate this issue. Leave blank if it's just "talk to this NPC".
    validations:
      required: false
  - type: upload
    id: savefile
    attributes:
      label: Optional Savefile / Savestate
      description: If you think it would be helpful please provide a .zip of your save file or savestate so we can test the bug, problem, or mistake you encountered.
    validations:
      required: false
