name: Text Wrapping
description: Text overflows from it's textbox
title: "[Bug]:"
labels: ["Text Wrapping"]
body:
  - type: upload
    id: screenshot
    attributes:
      label: Image
      description: Please provide an image of the of the bug, problem, or mistake you encountered. 
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide us with a description of the bug, problem, or mistake you encountered.
    validations:
      required: true
  - type: dropdown
    id: device
    attributes:
      label: Emulator or Flashcart
      description: Are you playing this on a flashcart or an emulator? When in doubt, it's an emulator.
      multiple: false
      options:
        - Emulator
        - Flashcart
    validations:
      required: true
  - type: input
    id: deviceinfo
    attributes:
      label: Emulator or Flashcart Info
      description: Flashcart| flashcart name, firmware, and device (GBA, DS lite, Game Cube). Emulator| Include name, version number, and device (Pc, 3ds, Android Phone). Also, if emulating use mGBA; VBA-M and Virtual Console are generally less accurate.
    validations:
      required: true
  - type: input
    id: patchversion
    attributes:
      label: Patch Version
      description: Which version of the patch were you using (including the date)?
    validations:
      required: true
  - type: dropdown
    id: gender
    attributes:
      label: Player Gender
      multiple: false
      options:
        - Boy
        - Girl
    validations:
      required: true
  - type: dropdown
    id: partner
    attributes:
      label: Partner Character
      multiple: false
      options:
        - RUN-DOR
        - Enzi
        - Killfith
        - Rufeel
    validations:
      required: true
  - type: input
    id: playername
    attributes:
      label: Player Character Name
      description: Type = if it's the default name. Please use these for special characters (Ⅰ|Ⅱ|Ⅲ|Ⅳ|Ⅴ|Ⅵ|Ⅶ|Ⅷ|Ⅸ|Ⅹ|♥|♪|★).
    validations:
      required: true
  - type: input
    id: playernick
    attributes:
      label: Player Character Nickname
      description: Leave blank if it's the same as your player character name. Type = if it's the default nickname. Please use these for special characters (Ⅰ|Ⅱ|Ⅲ|Ⅳ|Ⅴ|Ⅵ|Ⅶ|Ⅷ|Ⅸ|Ⅹ|♥|♪|★).
    validations:
      required: false
  - type: input
    id: beastname
    attributes:
      label: Partner Name
      description: Type = if it's the default partner name. Please use these for special characters (Ⅰ|Ⅱ|Ⅲ|Ⅳ|Ⅴ|Ⅵ|Ⅶ|Ⅷ|Ⅸ|Ⅹ|♥|♪|★).
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: How did you get this to happen?
      description: Please provide instructions for how to replicate this issue. Leave blank if it's just "talk to this NPC".
    validations:
      required: false
  - type: upload
    id: savefile
    attributes:
      label: Optional Savefile
      description: If you think it would be helpful please provide a .zip of your save file [.sav] so we can test the bug, problem, or mistake you encountered. 
    validations:
      required: false
