blank_issues_enabled: false
contact_links:
  - name: Summon Night Community Discord Bug Reports Guest Link
    url: https://discord.gg/mvmPAejeDa
    about: Please the link above if you arent in the discord to join as a guest. Then post your issue link in the #bug-reports channel
  - name: Summon Night Community Discord
    url: https://bounty.github.com/
    about: Click this if you want to join the discord normally.
  - name: Bug Reports Channel 
    url: https://discord.com/channels/378317019520565249/1532342850627567809
    about: Click this if you are already in the discord. Then post your issue link in the #bug-reports channel 
